<?php
	// ======================================== \
	// Mihalism Multi Forum Host v3.0.x
	// Copyright (c) 2007 Mihalism, Inc.
	// Developed by Albino, Craig, and Michael
	//
	// http://www.mihalism.com/product/mfh/
	// ======================================== /
	
	/* DO NOT EDIT THIS FILE */
	
	$mfhclass->info->phpbb_tables = array(
		"<# access_name #>_acl_groups",
		"<# access_name #>_acl_options",
		"<# access_name #>_acl_roles",
		"<# access_name #>_acl_roles_data",
		"<# access_name #>_acl_users",
		"<# access_name #>_attachments",
		"<# access_name #>_banlist",
		"<# access_name #>_bbcodes",
		"<# access_name #>_bookmarks",
		"<# access_name #>_bots",
		"<# access_name #>_config",
		"<# access_name #>_confirm",
		"<# access_name #>_disallow",
		"<# access_name #>_drafts",
		"<# access_name #>_extensions",
		"<# access_name #>_extension_groups",
		"<# access_name #>_forums",
		"<# access_name #>_forums_access",
		"<# access_name #>_forums_track",
		"<# access_name #>_forums_watch",
		"<# access_name #>_groups",
		"<# access_name #>_icons",
		"<# access_name #>_lang",
		"<# access_name #>_log",
		"<# access_name #>_moderator_cache",
		"<# access_name #>_modules",
		"<# access_name #>_poll_options",
		"<# access_name #>_poll_votes",
		"<# access_name #>_posts",
		"<# access_name #>_privmsgs",
		"<# access_name #>_privmsgs_folder",
		"<# access_name #>_privmsgs_rules",
		"<# access_name #>_privmsgs_to",
		"<# access_name #>_profile_fields",
		"<# access_name #>_profile_fields_data",
		"<# access_name #>_profile_fields_lang",
		"<# access_name #>_profile_lang",
		"<# access_name #>_ranks",
		"<# access_name #>_reports",
		"<# access_name #>_reports_reasons",
		"<# access_name #>_search_results",
		"<# access_name #>_search_wordlist",
		"<# access_name #>_search_wordmatch",
		"<# access_name #>_sessions",
		"<# access_name #>_sessions_keys",
		"<# access_name #>_sitelist",
		"<# access_name #>_smilies",
		"<# access_name #>_styles",
		"<# access_name #>_styles_imageset",
		"<# access_name #>_styles_imageset_data",
		"<# access_name #>_styles_template",
		"<# access_name #>_styles_template_data",
		"<# access_name #>_styles_theme",
		"<# access_name #>_topics",
		"<# access_name #>_topics_posted",
		"<# access_name #>_topics_track",
		"<# access_name #>_topics_watch",
		"<# access_name #>_users",
		"<# access_name #>_user_group",
		"<# access_name #>_warnings",
		"<# access_name #>_words",
		"<# access_name #>_zebra"
	);
	
?>
